Repository nextcloud/whiteboard, pull requests merged in 2024-09, with the labels that each got.

#129 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#142 feat: Add settings UI
  appinfo/info.xml
  appinfo/routes.php
  lib/Controller/SettingsController.php
  lib/Service/ConfigService.php
  lib/Service/JWTService.php
  lib/Settings/Admin.php
  lib/Settings/Section.php
  package-lock.json
  package.json
  src/settings.js
  src/settings/Settings.vue
  templates/admin.php
  tests/psalm-baseline.xml
  vite.config.ts
  websocket_server/SocketManager.js
Labels: enhancement, 3. to review

#143 chore/release 1.0.0 rc.1
  appinfo/info.xml
  websocket_server/AppManager.js
Labels: release

#156 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#157 fix: Include composer dependencies in the release bundle
  krankerl.toml
Labels: bug, 3. to review

#169 fix: Make template file creator registration compatible with 28/29
  lib/AppInfo/Application.php
  lib/Listener/RegisterTemplateCreatorListener.php
Labels: bug, 3. to review

#167 fix: Use proper server url parameter from the frontend
  lib/Controller/SettingsController.php
Labels: bug
