Repository nextcloud/whiteboard, pull requests merged in 2024-07, with the labels that each got.

#62 feat: Add metrics endpoint to publish socket.io metrics to prometheus
  .env.example
  package-lock.json
  package.json
  websocket_server/app.js
  websocket_server/socket.js
Labels: enhancement, backend

#64 [main] Update nextcloud/ocp dependency
  composer.json
  composer.lock
Labels: dependencies, 3. to review

#69 Migrate REUSE to TOML format
  .github/workflows/reuse.yml
  .reuse/dep5
  README.md
  REUSE.toml
Labels: documentation, 3. to review

#70 chore: update workflows from templates
  .github/workflows/appstore-build-publish.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/lint-stylelint.yml
  .github/workflows/node.yml
  .github/workflows/npm-audit-fix.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/psalm.yml
  .github/workflows/update-nextcloud-ocp.yml
Labels: dependencies, 3. to review, automated

#71 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#81 Add PR feedback action
  .github/workflows/pr-feedback.yml
Labels: 3. to review

#95 [main] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#82 Docker image build
  .github/workflows/docker.yml
  Dockerfile
Labels: enhancement
