Repository nextcloud/whiteboard, pull requests merged in 2024-08, with the labels that each got.

#101 [main] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#100 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#114 Feat/styling right click menu
  src/App.scss
Labels: 3. to review

#90 memory optimization
  .env.example
  package-lock.json
  package.json
  websocket_server/ApiService.js
  websocket_server/AppManager.js
  websocket_server/LRUCacheStrategy.js
  websocket_server/PrometheusDataManager.js
  websocket_server/RedisStrategy.js
  websocket_server/Room.js
  websocket_server/RoomDataManager.js
  websocket_server/ServerManager.js
  websocket_server/SharedTokenGenerator.js
  websocket_server/SocketDataManager.js
  websocket_server/SocketManager.js
  websocket_server/StorageManager.js
  websocket_server/StorageStrategy.js
  websocket_server/SystemMonitor.js
  websocket_server/Utils.js
  websocket_server/app.js
  websocket_server/auth.js
  websocket_server/main.js
  websocket_server/roomData.js
  websocket_server/server.js
  websocket_server/socket.js
  websocket_server/utils.js
Labels: enhancement, 3. to review

#111 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#126 [main] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review
