Repository nextcloud/whiteboard, pull requests merged in 2024-10, with the labels that each got.

#202 feat(l10n): Start translating the app
  .l10nignore
  .tx/config
  l10n/.gitkeep
Labels: 3. to review

#205 bump version to 1.0.3
  CHANGELOG.md
  appinfo/info.xml
  package.json
Labels: release

#146 test: Add vitest and some basic integration tests
  .github/workflows/node-test.yml
  package-lock.json
  package.json
  tests/integration/metrics.spec.mjs
  tests/integration/socket.spec.mjs
  vitest.config.js
  websocket_server/SocketManager.js
Labels: tests

#215 fix: use system theme if no ncTheme available
  src/App.tsx
Labels: bug

#223 [main] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#224 fix: Properly handle metrics aggregation with room data
  websocket_server/LRUCacheStrategy.js
  websocket_server/RedisStrategy.js
  websocket_server/SystemMonitor.js
Labels: bug, 3. to review

#206 fix: Proper fallback for app config methods on Nextcloud 28
  lib/Service/ConfigService.php
Labels: bug

#216 set viewmode if share is readonly
  src/App.tsx
  src/collaboration/collab.ts
Labels: bug

#210 docs/enhance
  README.md
Labels: documentation

#213 chore(readme): add exemplary configuration for Caddy v2
  README.md
Labels: 3. to review

#237 [main] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#241 feat(Dockerfile): do not pin alpine version
  Dockerfile
Labels: enhancement, 3. to review

#242 fix #183 typo in Readme for nginx reverse configuration
  README.md
Labels: documentation, 3. to review
