Repository nextcloud/whiteboard, pull requests merged in 2024-12, with the labels that each got.

#282 add reverse proxy config example for Apache >= 2.4.47
  README.md
Labels: feedback-requested

#283 [main] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#251 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#319 chore(CI): Updating reuse.yml workflow from template
  .github/workflows/reuse.yml
Labels: dependencies
