Repository nextcloud/whiteboard, pull requests merged in 2025-02, with the labels that each got.

#335 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#352 Add traefik configuration hints
  README.md
Labels: 3. to review

#361 Add playwright skeleton for e2e tests
  .github/workflows/playwright.yml
  appinfo/info.xml
  package-lock.json
  package.json
  playwright.config.ts
  playwright/e2e/viewer.spec.ts
  playwright/start-nextcloud-server.mjs
  playwright/support/fixtures/random-user.ts
  playwright/support/setup.ts
Labels: 3. to review, tests

#297 feat: Add setup check to verify whiteboard backend server version and connectivity
  lib/AppInfo/Application.php
  lib/Controller/SettingsController.php
  lib/Service/ConfigService.php
  lib/Settings/Admin.php
  lib/Settings/SetupCheck.php
  src/settings/Settings.vue
  websocket_server/AppManager.js
Labels: enhancement, 3. to review
