Repository nextcloud/whiteboard, pull requests merged in 2025-09, with the labels that each got.

#635 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#628 build: update node and npm engines versions
  package.json
Labels: dependencies

#559 screen recording + presentation mode
  .gitignore
  appinfo/routes.php
  lib/Controller/RecordingController.php
  lib/Service/File/GetFileServiceFactory.php
  lib/Service/JWTService.php
  package-lock.json
  package.json
  src/App.scss
  src/App.tsx
  src/components/DraggableDialog.tsx
  src/components/ExcalidrawMenu.tsx
  src/components/Presentation.tsx
  src/components/Recording.tsx
  src/hooks/useCollaboration.ts
  src/hooks/usePresentation.ts
  src/hooks/useRecording.ts
  src/hooks/useSync.ts
  src/main.tsx
  src/stores/useCollaborationStore.ts
  templates/recording.php
  websocket_server/Config.js
  websocket_server/RecordingService.js
  websocket_server/SharedTokenGenerator.js
  websocket_server/SocketManager.js
Labels: enhancement, 3. to review, 2. developing

#546 feat: set created_by customData on new elements
  package-lock.json
  package.json
  src/App.tsx
  src/components/AssistantDialog.vue
  src/components/CreatorDisplay.scss
  src/components/CreatorDisplay.tsx
  src/components/CreatorMenuItem.module.scss
  src/components/CreatorMenuItem.tsx
  src/components/ExcalidrawMenu.tsx
  src/components/Presentation.tsx
  src/components/Recording.tsx
  src/hooks/useAssistant.tsx
  src/hooks/useBoardDataManager.ts
  src/hooks/useCollaboration.ts
  src/hooks/useElementCreatorTracking.ts
  src/hooks/useFiles.ts
  src/hooks/usePresentation.ts
  src/hooks/useSmartPicker.tsx
  src/hooks/useSync.ts
  src/stores/useCreatorDisplayStore.ts
  src/stores/useLangStore.ts
  src/types/whiteboard.d.ts
  src/utils.ts
  src/utils/reconcileElements.ts
  vite.config.ts
Labels: enhancement
